image: go:1.6.2

stages:
  - build
  - test
  - deploy
#
# install-go:
#   stage: install-environment
#   script:
#     - export CURRENT_BUILD_PATH=$(pwd)
#     - echo $PATH
#     - rm -rf $HOME/golang
#     - rm -rf $HOME/gopath
#     - mkdir -p $HOME/golang # for GOROOT (contains the Go binary & core packages)
#     - mkdir -p $HOME/gopath # for GOPATH (contains code and external packages)
#     - curl http://storage.googleapis.com/golang/go1.5.2.linux-amd64.tar.gz 2>/dev/null > go1.5.2.linux-amd64.tar.gz
#     - tar -C $HOME/golang -xzf go1.5.2.linux-amd64.tar.gz
#     - export GOROOT=$HOME/golang/go
#     - export GOPATH=$HOME/gopath
#     - export PATH=$PATH:$GOROOT/bin
#     - export PATH=$PATH:$GOPATH/bin
#     - (if [[ "$(go version)" == *"go version go1.5"* ]]; then echo "âœ“ Go binary installed!"; else echo "Go binary not installed"; exit -1; fi);
#     - go version
#     - echo $PATH
#     - go env
#     - which go

compile:
  stage: build
  script:
    - cd $CURRENT_BUILD_PATH
    - go build
  only:
    - master
  tags:
    - docker


test:
  stage: test
  script:
    - cd $CURRENT_BUILD_PATH
    - go test
